name: vitalvision
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Icons iOS
  cupertino_icons: ^1.0.8
  http: ^1.1.0

  # Cámara en tiempo real para detección
  camera: ^0.11.1

  
  # TensorFlow Lite para IA offline
  tflite_flutter: ^0.10.0

  # Permisos (cámara, micrófono, contactos, etc.)
  permission_handler: ^12.0.1

  # Acceso a almacenamiento local
  path_provider: ^2.0.0
  
  # Image processing 
  image: ^3.0.0

  # Overlay notifications
  overlay_support: ^1.2.1

  # Gestión de estado
  flutter_riverpod: ^2.3.7

  # Conectividad
  connectivity_plus: ^4.0.0

  # Text-to-Speech offline estilo Alexa
  flutter_tts: ^4.2.0

  # Llamar al contacto de emergencia directamente
  url_launcher: ^6.1.10 

  # Acceso a contactos
  flutter_contacts: ^1.1.9+2

  # Shared Preferences
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/models/best_float16.tflite
    - assets/models/labels.txt

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
